import KanaFlag.ADD_DOUBLE_CONSONANT

val HIRAGANA_MAPPINGS: PrefixTree = KanaTreeBuilder(sokuon = "っ").apply {
    // Only k, s, t, and p constants get doubled (possibly with rare exceptions)

    put("a", "あ")
    put("i", "い")
    put("u", "う")
    put("e", "え")
    put("o", "お")
    put("ka", "か", ADD_DOUBLE_CONSONANT)
    put("ki", "き", ADD_DOUBLE_CONSONANT)
    put("ku", "く", ADD_DOUBLE_CONSONANT)
    put("ke", "け", ADD_DOUBLE_CONSONANT)
    put("ko", "こ", ADD_DOUBLE_CONSONANT)
    put("kya", "きゃ", ADD_DOUBLE_CONSONANT)
    put("kyu", "きゅ", ADD_DOUBLE_CONSONANT)
    put("kyo", "きょ", ADD_DOUBLE_CONSONANT)
    put("sa", "さ", ADD_DOUBLE_CONSONANT)
    put("shi", "し", ADD_DOUBLE_CONSONANT)
    put("su", "す", ADD_DOUBLE_CONSONANT)
    put("se", "せ", ADD_DOUBLE_CONSONANT)
    put("so", "そ", ADD_DOUBLE_CONSONANT)
    put("sha", "しゃ", ADD_DOUBLE_CONSONANT)
    put("shu", "しゅ", ADD_DOUBLE_CONSONANT)
    put("sho", "しょ", ADD_DOUBLE_CONSONANT)
    put("ta", "た", ADD_DOUBLE_CONSONANT)
    put("chi", "ち", ADD_DOUBLE_CONSONANT)
    put("tsu", "つ", ADD_DOUBLE_CONSONANT)
    put("te", "て", ADD_DOUBLE_CONSONANT)
    put("to", "と", ADD_DOUBLE_CONSONANT)
    put("cha", "ちゃ", ADD_DOUBLE_CONSONANT)
    put("chu", "ちゅ", ADD_DOUBLE_CONSONANT)
    put("cho", "ちょ", ADD_DOUBLE_CONSONANT)
    put("na", "な")
    put("ni", "に")
    put("nu", "ぬ")
    put("ne", "ね")
    put("no", "の")
    put("nya", "にゃ")
    put("nyu", "にゅ")
    put("nyo", "にょ")
    put("ha", "は")
    put("hi", "ひ")
    put("fu", "ふ")
    put("he", "へ")
    put("ho", "ほ")
    put("hya", "ひゃ")
    put("hyu", "ひゅ")
    put("hyo", "ひょ")
    put("ma", "ま")
    put("mi", "み")
    put("mu", "む")
    put("me", "め")
    put("mo", "も")
    put("mya", "みゃ")
    put("myu", "みゅ")
    put("myo", "みょ")
    put("ya", "や")
    put("yu", "ゆ")
    put("yo", "よ")
    put("ra", "ら")
    put("ri", "り")
    put("ru", "る")
    put("re", "れ")
    put("ro", "ろ")
    put("rya", "りゃ")
    put("ryu", "りゅ")
    put("ryo", "りょ")
    put("wa", "わ")
    put("wo", "を")
    put("ga", "が")
    put("gi", "ぎ")
    put("gu", "ぐ")
    put("ge", "げ")
    put("go", "ご")
    put("gya", "ぎゃ")
    put("gyu", "ぎゅ")
    put("gyo", "ぎょ")
    put("za", "ざ")
    put("ji", "じ")
    put("zu", "ず")
    put("ze", "ぜ")
    put("zo", "ぞ")
    put("ja", "じゃ")
    put("ju", "じゅ")
    put("jo", "じょ")
    put("da", "だ")
    put("de", "で")
    put("do", "ど")
    put("ba", "ば")
    put("bi", "び")
    put("bu", "ぶ")
    put("be", "べ")
    put("bo", "ぼ")
    put("bya", "びゃ")
    put("byu", "びゅ")
    put("byo", "びょ")
    put("pa", "ぱ", ADD_DOUBLE_CONSONANT)
    put("pi", "ぴ", ADD_DOUBLE_CONSONANT)
    put("pu", "ぷ", ADD_DOUBLE_CONSONANT)
    put("pe", "ぺ", ADD_DOUBLE_CONSONANT)
    put("po", "ぽ", ADD_DOUBLE_CONSONANT)
    put("pya", "ぴゃ", ADD_DOUBLE_CONSONANT)
    put("pyu", "ぴゅ", ADD_DOUBLE_CONSONANT)
    put("pyo", "ぴょ", ADD_DOUBLE_CONSONANT)
    put("n", "ん")

    // "duplicates"
    put("zu", "づ")
    put("ji", "ぢ")
    put("ja", "ぢゃ")
    put("ju", "ぢゅ")
    put("jo", "ぢょ")
}.build()

val KATAKANA_MAPPINGS = KanaTreeBuilder("ッ").apply {
    put("", "ア")
    put("", "イ")
    put("", "ウ")
    put("", "エ")
    put("", "オ")
    put("", "カ")
    put("", "キ")
    put("", "ク")
    put("", "ケ")
    put("", "コ")
    put("", "キャ")
    put("", "キュ")
    put("", "キョ")
    put("", "サ")
    put("", "シ")
    put("", "ス")
    put("", "セ")
    put("", "ソ")
    put("", "シャ")
    put("", "シュ")
    put("", "ショ")
    put("", "タ")
    put("", "チ")
    put("", "ツ")
    put("", "テ")
    put("", "ト")
    put("", "チャ")
    put("", "チュ")
    put("", "チョ")
    put("", "ナ")
    put("", "ニ")
    put("", "ヌ")
    put("", "ネ")
    put("", "ノ")
    put("", "ニャ")
    put("", "ニュ")
    put("", "ニョ")
    put("", "ハ")
    put("", "ヒ")
    put("", "フ")
    put("", "ヘ")
    put("", "ホ")
    put("", "ヒャ")
    put("", "ヒュ")
    put("", "ヒョ")
    put("", "マ")
    put("", "ミ")
    put("", "ム")
    put("", "メ")
    put("", "モ")
    put("", "ミャ")
    put("", "ミュ")
    put("", "ミョ")
    put("", "ヤ")
    put("", "𛄠")
    put("", "ユ")
    put("", "エ")
    put("", "ヨ")
    put("", "ラ")
    put("", "リ")
    put("", "ル")
    put("", "レ")
    put("", "ロ")
    put("", "リャ")
    put("", "リュ")
    put("", "リョ")
    put("", "ワ")
    put("", "ヰ")
    put("", "𛄢")
    put("", "ヱ")
    put("", "ヲ")
    put("", "ガ")
    put("", "ギ")
    put("", "グ")
    put("", "ゲ")
    put("", "ゴ")
    put("", "ギャ")
    put("", "ギュ")
    put("", "ギョ")
    put("", "ザ")
    put("", "ジ")
    put("", "ズ")
    put("", "ゼ")
    put("", "ゾ")
    put("", "ジャ")
    put("", "ジュ")
    put("", "ジョ")
    put("", "ダ")
    put("", "ヂ")
    put("", "ヅ")
    put("", "デ")
    put("", "ド")
    put("", "ヂャ")
    put("", "ヂュ")
    put("", "ヂョ")
    put("", "バ")
    put("", "ビ")
    put("", "ブ")
    put("", "ベ")
    put("", "ボ")
    put("", "ビャ")
    put("", "ビュ")
    put("", "ビョ")
    put("", "パ")
    put("", "ピ")
    put("", "プ")
    put("", "ペ")
    put("", "ポ")
    put("", "ピャ")
    put("", "ピュ")
    put("", "ピョ")
    put("", "ン")
    put("", "")
    put("", "ヿ")
    put("", "")
    put("", "/")
    put("", "")
    put("", "")
    put("", "゙")
    put("", "ッ")
    put("", "ー")
    put("", "ヽ")
    put("", "〱")
    put("", "ヾ")
    put("", "〱゙")
    put("", "ヽ゚")
    put("", "〱゚")
}