import KanaFlag.ADD_DOUBLE_CONSONANT

val HIRAGANA_MAPPINGS: PrefixTree = KanaTreeBuilder(sokuon = "っ").apply {
    // Only k, s, t, and p constants get doubled (possibly with rare exceptions)

    put("a", "あ")
    put("i", "い")
    put("u", "う")
    put("e", "え")
    put("o", "お")
    put("ka", "か", ADD_DOUBLE_CONSONANT)
    put("ki", "き", ADD_DOUBLE_CONSONANT)
    put("ku", "く", ADD_DOUBLE_CONSONANT)
    put("ke", "け", ADD_DOUBLE_CONSONANT)
    put("ko", "こ", ADD_DOUBLE_CONSONANT)
    put("kya", "きゃ", ADD_DOUBLE_CONSONANT)
    put("kyu", "きゅ", ADD_DOUBLE_CONSONANT)
    put("kyo", "きょ", ADD_DOUBLE_CONSONANT)
    put("sa", "さ", ADD_DOUBLE_CONSONANT)
    put("shi", "し", ADD_DOUBLE_CONSONANT)
    put("su", "す", ADD_DOUBLE_CONSONANT)
    put("se", "せ", ADD_DOUBLE_CONSONANT)
    put("so", "そ", ADD_DOUBLE_CONSONANT)
    put("sha", "しゃ", ADD_DOUBLE_CONSONANT)
    put("shu", "しゅ", ADD_DOUBLE_CONSONANT)
    put("sho", "しょ", ADD_DOUBLE_CONSONANT)
    put("ta", "た", ADD_DOUBLE_CONSONANT)
    put("chi", "ち", ADD_DOUBLE_CONSONANT)
    put("tsu", "つ", ADD_DOUBLE_CONSONANT)
    put("te", "て", ADD_DOUBLE_CONSONANT)
    put("to", "と", ADD_DOUBLE_CONSONANT)
    put("cha", "ちゃ", ADD_DOUBLE_CONSONANT)
    put("chu", "ちゅ", ADD_DOUBLE_CONSONANT)
    put("cho", "ちょ", ADD_DOUBLE_CONSONANT)
    put("na", "な")
    put("ni", "に")
    put("nu", "ぬ")
    put("ne", "ね")
    put("no", "の")
    put("nya", "にゃ")
    put("nyu", "にゅ")
    put("nyo", "にょ")
    put("ha", "は")
    put("hi", "ひ")
    put("fu", "ふ")
    put("he", "へ")
    put("ho", "ほ")
    put("hya", "ひゃ")
    put("hyu", "ひゅ")
    put("hyo", "ひょ")
    put("ma", "ま")
    put("mi", "み")
    put("mu", "む")
    put("me", "め")
    put("mo", "も")
    put("mya", "みゃ")
    put("myu", "みゅ")
    put("myo", "みょ")
    put("ya", "や")
    put("yu", "ゆ")
    put("yo", "よ")
    put("ra", "ら")
    put("ri", "り")
    put("ru", "る")
    put("re", "れ")
    put("ro", "ろ")
    put("rya", "りゃ")
    put("ryu", "りゅ")
    put("ryo", "りょ")
    put("wa", "わ")
    put("wo", "を")
    put("ga", "が")
    put("gi", "ぎ")
    put("gu", "ぐ")
    put("ge", "げ")
    put("go", "ご")
    put("gya", "ぎゃ")
    put("gyu", "ぎゅ")
    put("gyo", "ぎょ")
    put("za", "ざ")
    put("ji", "じ")
    put("zu", "ず")
    put("ze", "ぜ")
    put("zo", "ぞ")
    put("ja", "じゃ")
    put("ju", "じゅ")
    put("jo", "じょ")
    put("da", "だ")
    put("de", "で")
    put("do", "ど")
    put("ba", "ば")
    put("bi", "び")
    put("bu", "ぶ")
    put("be", "べ")
    put("bo", "ぼ")
    put("bya", "びゃ")
    put("byu", "びゅ")
    put("byo", "びょ")
    put("pa", "ぱ", ADD_DOUBLE_CONSONANT)
    put("pi", "ぴ", ADD_DOUBLE_CONSONANT)
    put("pu", "ぷ", ADD_DOUBLE_CONSONANT)
    put("pe", "ぺ", ADD_DOUBLE_CONSONANT)
    put("po", "ぽ", ADD_DOUBLE_CONSONANT)
    put("pya", "ぴゃ", ADD_DOUBLE_CONSONANT)
    put("pyu", "ぴゅ", ADD_DOUBLE_CONSONANT)
    put("pyo", "ぴょ", ADD_DOUBLE_CONSONANT)
    put("n", "ん")

    // "duplicates"
    put("zu", "づ")
    put("ji", "ぢ")
    put("ja", "ぢゃ")
    put("ju", "ぢゅ")
    put("jo", "ぢょ")
}.build()

val KATAKANA_MAPPINGS = KanaTreeBuilder("ッ").apply {
    put("a", "ア")
    put("i", "イ")
    put("u", "ウ")
    put("e", "エ")
    put("o", "オ")
    put("ka", "カ", ADD_DOUBLE_CONSONANT)
    put("ki", "キ", ADD_DOUBLE_CONSONANT)
    put("ku", "ク", ADD_DOUBLE_CONSONANT)
    put("ke", "ケ", ADD_DOUBLE_CONSONANT)
    put("ko", "コ", ADD_DOUBLE_CONSONANT)
    put("kya", "キャ", ADD_DOUBLE_CONSONANT)
    put("kyu", "キュ", ADD_DOUBLE_CONSONANT)
    put("kyo", "キョ", ADD_DOUBLE_CONSONANT)
    put("sa", "サ", ADD_DOUBLE_CONSONANT)
    put("shi", "シ", ADD_DOUBLE_CONSONANT)
    put("su", "ス", ADD_DOUBLE_CONSONANT)
    put("se", "セ", ADD_DOUBLE_CONSONANT)
    put("so", "ソ", ADD_DOUBLE_CONSONANT)
    put("sha", "シャ", ADD_DOUBLE_CONSONANT)
    put("shu", "シュ", ADD_DOUBLE_CONSONANT)
    put("sho", "ショ", ADD_DOUBLE_CONSONANT)
    put("ta", "タ", ADD_DOUBLE_CONSONANT)
    put("chi", "チ", ADD_DOUBLE_CONSONANT)
    put("tsu", "ツ", ADD_DOUBLE_CONSONANT)
    put("te", "テ", ADD_DOUBLE_CONSONANT)
    put("to", "ト", ADD_DOUBLE_CONSONANT)
    put("cha", "チャ", ADD_DOUBLE_CONSONANT)
    put("chu", "チュ", ADD_DOUBLE_CONSONANT)
    put("cho", "チョ", ADD_DOUBLE_CONSONANT)
    put("na", "ナ")
    put("ni", "ニ")
    put("nu", "ヌ")
    put("ne", "ネ")
    put("no", "ノ")
    put("nya", "ニャ")
    put("nyu", "ニュ")
    put("nyo", "ニョ")
    put("ha", "ハ")
    put("hi", "ヒ")
    put("fu", "フ")
    put("he", "ヘ")
    put("ho", "ホ")
    put("hya", "ヒャ")
    put("hyu", "ヒュ")
    put("hyo", "ヒョ")
    put("ma", "マ")
    put("mi", "ミ")
    put("mu", "ム")
    put("me", "メ")
    put("mo", "モ")
    put("mya", "ミャ")
    put("myu", "ミュ")
    put("myo", "ミョ")
    put("ya", "ヤ")
    put("yu", "ユ")
    put("yo", "ヨ")
    put("ra", "ラ")
    put("ri", "リ")
    put("ru", "ル")
    put("re", "レ")
    put("ro", "ロ")
    put("rya", "リャ")
    put("ryu", "リュ")
    put("ryo", "リョ")
    put("wa", "ワ")
    put("wo", "ヲ")
    put("ga", "ガ")
    put("gi", "ギ")
    put("gu", "グ")
    put("ge", "ゲ")
    put("go", "ゴ")
    put("gya", "ギャ")
    put("gyu", "ギュ")
    put("gyo", "ギョ")
    put("za", "ザ")
    put("ji", "ジ")
    put("zu", "ズ")
    put("ze", "ゼ")
    put("zo", "ゾ")
    put("ja", "ジャ")
    put("ju", "ジュ")
    put("jo", "ジョ")
    put("da", "ダ")
    put("de", "デ")
    put("do", "ド")
    put("ba", "バ")
    put("bi", "ビ")
    put("bu", "ブ")
    put("be", "ベ")
    put("bo", "ボ")
    put("bya", "ビャ")
    put("byu", "ビュ")
    put("byo", "ビョ")
    put("pa", "パ", ADD_DOUBLE_CONSONANT)
    put("pi", "ピ", ADD_DOUBLE_CONSONANT)
    put("pu", "プ", ADD_DOUBLE_CONSONANT)
    put("pe", "ペ", ADD_DOUBLE_CONSONANT)
    put("po", "ポ", ADD_DOUBLE_CONSONANT)
    put("pya", "ピャ", ADD_DOUBLE_CONSONANT)
    put("pyu", "ピュ", ADD_DOUBLE_CONSONANT)
    put("pyo", "ピョ", ADD_DOUBLE_CONSONANT)
    put("n", "ン")

    // "duplicates"
    put("ji", "ヂ")
    put("zu", "ヅ")
    put("ja", "ヂャ")
    put("ju", "ヂュ")
    put("jo", "ヂョ")
}.build()
