package io.dge.kanaizer.tree

import io.dge.kanaizer.tree.KanaFlag.*


val HIRAGANA_MAPPINGS: PrefixTree = KanaTreeBuilder(sokuon = "っ").apply {
    // Only k, s, t, and p constants get doubled (possibly with rare exceptions)

    put("a", "あ")
    put("i", "い")
    put("u", "う")
    put("e", "え")
    put("o", "お")
    put("ka", "か", ADD_DOUBLE_CONSONANT)
    put("ki", "き", ADD_DOUBLE_CONSONANT)
    put("ku", "く", ADD_DOUBLE_CONSONANT)
    put("ke", "け", ADD_DOUBLE_CONSONANT)
    put("ko", "こ", ADD_DOUBLE_CONSONANT)
    put("kya", "きゃ", ADD_DOUBLE_CONSONANT)
    put("kyu", "きゅ", ADD_DOUBLE_CONSONANT)
    put("kyo", "きょ", ADD_DOUBLE_CONSONANT)
    put("sa", "さ", ADD_DOUBLE_CONSONANT)
    put("shi", "し", ADD_DOUBLE_CONSONANT)
    put("su", "す", ADD_DOUBLE_CONSONANT)
    put("se", "せ", ADD_DOUBLE_CONSONANT)
    put("so", "そ", ADD_DOUBLE_CONSONANT)
    put("sha", "しゃ", ADD_DOUBLE_CONSONANT)
    put("shu", "しゅ", ADD_DOUBLE_CONSONANT)
    put("sho", "しょ", ADD_DOUBLE_CONSONANT)
    put("ta", "た", ADD_DOUBLE_CONSONANT)
    put("chi", "ち", ADD_DOUBLE_CONSONANT)
    put("tsu", "つ", ADD_DOUBLE_CONSONANT)
    put("te", "て", ADD_DOUBLE_CONSONANT)
    put("to", "と", ADD_DOUBLE_CONSONANT)
    put("cha", "ちゃ", ADD_DOUBLE_CONSONANT)
    put("chu", "ちゅ", ADD_DOUBLE_CONSONANT)
    put("cho", "ちょ", ADD_DOUBLE_CONSONANT)
    put("na", "な")
    put("ni", "に")
    put("nu", "ぬ")
    put("ne", "ね")
    put("no", "の")
    put("nya", "にゃ")
    put("nyu", "にゅ")
    put("nyo", "にょ")
    put("ha", "は")
    put("hi", "ひ")
    put("fu", "ふ")
    put("he", "へ")
    put("ho", "ほ")
    put("hya", "ひゃ")
    put("hyu", "ひゅ")
    put("hyo", "ひょ")
    put("ma", "ま")
    put("mi", "み")
    put("mu", "む")
    put("me", "め")
    put("mo", "も")
    put("mya", "みゃ")
    put("myu", "みゅ")
    put("myo", "みょ")
    put("ya", "や")
    put("yu", "ゆ")
    put("yo", "よ")
    put("ra", "ら")
    put("ri", "り")
    put("ru", "る")
    put("re", "れ")
    put("ro", "ろ")
    put("rya", "りゃ")
    put("ryu", "りゅ")
    put("ryo", "りょ")
    put("wa", "わ")
    put("wo", "を")
    put("ga", "が")
    put("gi", "ぎ")
    put("gu", "ぐ")
    put("ge", "げ")
    put("go", "ご")
    put("gya", "ぎゃ")
    put("gyu", "ぎゅ")
    put("gyo", "ぎょ")
    put("za", "ざ")
    put("ji", "じ")
    put("zu", "ず")
    put("ze", "ぜ")
    put("zo", "ぞ")
    put("ja", "じゃ")
    put("ju", "じゅ")
    put("jo", "じょ")
    put("da", "だ")
    put("de", "で")
    put("do", "ど")
    put("ba", "ば")
    put("bi", "び")
    put("bu", "ぶ")
    put("be", "べ")
    put("bo", "ぼ")
    put("bya", "びゃ")
    put("byu", "びゅ")
    put("byo", "びょ")
    put("pa", "ぱ", ADD_DOUBLE_CONSONANT)
    put("pi", "ぴ", ADD_DOUBLE_CONSONANT)
    put("pu", "ぷ", ADD_DOUBLE_CONSONANT)
    put("pe", "ぺ", ADD_DOUBLE_CONSONANT)
    put("po", "ぽ", ADD_DOUBLE_CONSONANT)
    put("pya", "ぴゃ", ADD_DOUBLE_CONSONANT)
    put("pyu", "ぴゅ", ADD_DOUBLE_CONSONANT)
    put("pyo", "ぴょ", ADD_DOUBLE_CONSONANT)
    put("n", "ん")

    // "duplicates"
    put("zu", "づ")
    put("ji", "ぢ")
    put("ja", "ぢゃ")
    put("ju", "ぢゅ")
    put("jo", "ぢょ")
}.build()

val KATAKANA_MAPPINGS: PrefixTree = KanaTreeBuilder(sokuon = "ッ", choonpu = "ー").apply {
    put("a", "ア", ADD_LONG_VOWEL)
    put("i", "イ", ADD_LONG_VOWEL)
    put("u", "ウ", ADD_LONG_VOWEL)
    put("e", "エ", ADD_LONG_VOWEL)
    put("o", "オ", ADD_LONG_VOWEL)
    put("ka", "カ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("ki", "キ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("ku", "ク", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("ke", "ケ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("ko", "コ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("kya", "キャ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("kyu", "キュ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("kyo", "キョ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("sa", "サ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("shi", "シ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("su", "ス", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("se", "セ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("so", "ソ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("sha", "シャ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("shu", "シュ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("sho", "ショ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("ta", "タ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("chi", "チ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("tsu", "ツ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("te", "テ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("to", "ト", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("cha", "チャ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("chu", "チュ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("cho", "チョ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("na", "ナ", ADD_LONG_VOWEL)
    put("ni", "ニ", ADD_LONG_VOWEL)
    put("nu", "ヌ", ADD_LONG_VOWEL)
    put("ne", "ネ", ADD_LONG_VOWEL)
    put("no", "ノ", ADD_LONG_VOWEL)
    put("nya", "ニャ", ADD_LONG_VOWEL)
    put("nyu", "ニュ", ADD_LONG_VOWEL)
    put("nyo", "ニョ", ADD_LONG_VOWEL)
    put("ha", "ハ", ADD_LONG_VOWEL)
    put("hi", "ヒ", ADD_LONG_VOWEL)
    put("fu", "フ", ADD_LONG_VOWEL)
    put("he", "ヘ", ADD_LONG_VOWEL)
    put("ho", "ホ", ADD_LONG_VOWEL)
    put("hya", "ヒャ", ADD_LONG_VOWEL)
    put("hyu", "ヒュ", ADD_LONG_VOWEL)
    put("hyo", "ヒョ", ADD_LONG_VOWEL)
    put("ma", "マ", ADD_LONG_VOWEL)
    put("mi", "ミ", ADD_LONG_VOWEL)
    put("mu", "ム", ADD_LONG_VOWEL)
    put("me", "メ", ADD_LONG_VOWEL)
    put("mo", "モ", ADD_LONG_VOWEL)
    put("mya", "ミャ", ADD_LONG_VOWEL)
    put("myu", "ミュ", ADD_LONG_VOWEL)
    put("myo", "ミョ", ADD_LONG_VOWEL)
    put("ya", "ヤ", ADD_LONG_VOWEL)
    put("yu", "ユ", ADD_LONG_VOWEL)
    put("yo", "ヨ", ADD_LONG_VOWEL)
    put("ra", "ラ", ADD_LONG_VOWEL)
    put("ri", "リ", ADD_LONG_VOWEL)
    put("ru", "ル", ADD_LONG_VOWEL)
    put("re", "レ", ADD_LONG_VOWEL)
    put("ro", "ロ", ADD_LONG_VOWEL)
    put("rya", "リャ", ADD_LONG_VOWEL)
    put("ryu", "リュ", ADD_LONG_VOWEL)
    put("ryo", "リョ", ADD_LONG_VOWEL)
    put("wa", "ワ", ADD_LONG_VOWEL)
    put("wo", "ヲ", ADD_LONG_VOWEL)
    put("ga", "ガ", ADD_LONG_VOWEL)
    put("gi", "ギ", ADD_LONG_VOWEL)
    put("gu", "グ", ADD_LONG_VOWEL)
    put("ge", "ゲ", ADD_LONG_VOWEL)
    put("go", "ゴ", ADD_LONG_VOWEL)
    put("gya", "ギャ", ADD_LONG_VOWEL)
    put("gyu", "ギュ", ADD_LONG_VOWEL)
    put("gyo", "ギョ", ADD_LONG_VOWEL)
    put("za", "ザ", ADD_LONG_VOWEL)
    put("ji", "ジ", ADD_LONG_VOWEL)
    put("zu", "ズ", ADD_LONG_VOWEL)
    put("ze", "ゼ", ADD_LONG_VOWEL)
    put("zo", "ゾ", ADD_LONG_VOWEL)
    put("ja", "ジャ", ADD_LONG_VOWEL)
    put("ju", "ジュ", ADD_LONG_VOWEL)
    put("jo", "ジョ", ADD_LONG_VOWEL)
    put("da", "ダ", ADD_LONG_VOWEL)
    put("de", "デ", ADD_LONG_VOWEL)
    put("do", "ド", ADD_LONG_VOWEL)
    put("ba", "バ", ADD_LONG_VOWEL)
    put("bi", "ビ", ADD_LONG_VOWEL)
    put("bu", "ブ", ADD_LONG_VOWEL)
    put("be", "ベ", ADD_LONG_VOWEL)
    put("bo", "ボ", ADD_LONG_VOWEL)
    put("bya", "ビャ", ADD_LONG_VOWEL)
    put("byu", "ビュ", ADD_LONG_VOWEL)
    put("byo", "ビョ", ADD_LONG_VOWEL)
    put("pa", "パ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("pi", "ピ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("pu", "プ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("pe", "ペ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("po", "ポ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("pya", "ピャ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("pyu", "ピュ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("pyo", "ピョ", ADD_DOUBLE_CONSONANT, ADD_LONG_VOWEL)
    put("n", "ン")

    // "duplicates"
    put("ji", "ヂ", ADD_LONG_VOWEL)
    put("zu", "ヅ", ADD_LONG_VOWEL)
    put("ja", "ヂャ", ADD_LONG_VOWEL)
    put("ju", "ヂュ", ADD_LONG_VOWEL)
    put("jo", "ヂョ", ADD_LONG_VOWEL)
}.build()
